version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: consumer-producer
      MYSQL_ROOT_PASSWORD: 31323334
      MYSQL_ROOT_HOST: '%'
    volumes:
     - ./my-sql:/var/lib/mysql
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  app:
      restart: on-failure
      build: ./
      expose:
        - "8000"
      ports:
        - 8000:8000
      environment:
        WAIT_HOSTS: mysql:3306
        DB_PASSWORD: 31323334
        DB_USER: root
        DB_NAME: consumer-producer
        DB_HOST: docker-mysql:3306

      depends_on:
        - docker-mysql